### ISSUE TITLE
 No module named 'joint_helper'

### ISSUE THREAD

**Issue by MrRace** [SVAIGBA/TwASP#2]
Run `python twasp_main.py --do_predict --input_file=./sample_data/sentence.txt --output_file=./sample_data/sentece.txt.out --eval_model=./models/TwASP.ZEN.UD1.v1.0.pt`
Come the error below:
```
    result = unpickler.load()
ModuleNotFoundError: No module named 'joint_helper'
```
My torch versins:
```
pytorch-ranger         0.1.1              
torch                  1.1.0              
torch-optimizer        0.0.1a13           
torchtext              0.5.0              
torchvision            0.6.0a0+82fd1c8 
```

**Comment by yuanheTian** [comment]
Thank you for pointing out. 

Did you meet this bug with our latest code? We changed our filename from "joint_helper.py" to "twasp_helper.py" in one update (we also change the filename of "joint_main.py", "joint_model.py", "joint_eval.py" in the same way). It seems that in some cases, this change makes the code fail to load our pre-trained model. We will check this problem. 

The quickest way to solve this issue is to change the filenames back to the old one. That is, change the current "twasp_helper.py" filename back to "joint_helper.py".

**Comment by MrRace** [comment]
@yuanheTian  Yeah, I just copy a new file named `joint_helper.py` from `twasp_helper.py` and it can work now.
